
install: 
	mkdir -p /usr/share/eniam/theories
	mkdir -p /usr/share/eniam/theories/numbers
	cp numbers/data/*  /usr/share/eniam/theories/numbers
	mkdir -p /usr/share/eniam/theories/time
	cp time/data/*  /usr/share/eniam/theories/time
	mkdir -p /usr/share/eniam/theories/alpha
	cp alpha/data/*  /usr/share/eniam/theories/alpha
	mkdir -p /usr/share/eniam/theories/aux
	cp aux/data/*  /usr/share/eniam/theories/aux
#	mkdir -p /usr/share/eniam/theories/persons
#	cp persons/data/*  /usr/share/eniam/theories/persons

